const {
  HTMLField,
  SchemaField,
  NumberField,
  StringField,
  FilePathField,
  ArrayField,
  BooleanField,
} = foundry.data.fields;

export class CharacterData extends foundry.abstract.TypeDataModel {
  static defineSchema() {
    return {
      hp: new SchemaField({
        value: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 10,
        }),
        min: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 0,
        }),
        max: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 10,
        }),
        adj: new NumberField({
          required: false,
          integer: true,
          min: 0,
          initial: 0,
        }),
      }),
      stats: new SchemaField({
        siz: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          formula: new StringField({ required: false }),
        }),
        dex: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        str: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        con: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        app: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
      }),
      coatOfArms: new FilePathField({
        required: true,
        categories: ["IMAGE"],
        initial: "systems/Pendragon/assets/Icons/checked-shield.svg",
      }),
      born: new NumberField({
        required: true,
        integer: true,
        min: 0,
        initial: 487,
      }),
      died: new NumberField({
        required: false,
        integer: true,
        min: 0,
        initial: 0,
      }),
      aggravDam: new NumberField({
        required: false,
        integer: true,
        min: 0,
        initial: 0,
      }),
      deterDam: new NumberField({
        required: false,
        integer: true,
        min: 0,
        initial: 0,
      }),
      beauty: new NumberField({
        required: false,
        integer: true,
        min: 0,
        initial: 0,
      }),
      prestige: new NumberField({
        required: false,
        integer: true,
        min: 0,
        initial: 0,
      }),
      damAdj: new NumberField({
        required: false,
        integer: true,
        min: 0,
        initial: 0,
      }),
      moveAdj: new NumberField({
        required: false,
        integer: true,
        min: 0,
        initial: 0,
      }),
      armourAdj: new NumberField({
        required: false,
        integer: true,
        min: 0,
        initial: 0,
      }),
      impoverished: new NumberField({
        required: false,
        integer: true,
        min: 0,
        initial: 0,
      }),
      lord: new StringField(),
      class: new StringField(),
      parentclass: new StringField(),
      sol: new StringField({ initial: "ordinary" }),
      culture: new StringField(),
      religion: new StringField(),
      homeland: new StringField(),
      home: new StringField(),
      family: new StringField(),
      gender: new StringField(),
      features: new StringField(),
      equestrian: new StringField(),
      heraldry: new StringField(),
      heir: new BooleanField(),
      lock: new BooleanField(),
      motto: new StringField(),
      battlePos: new StringField({ inital: "0" }),
      fieldPos: new StringField({ initial: "0" }),
      background: new HTMLField(),
      money: new SchemaField({
        libra: new NumberField({ integer: true }),
        denarii: new NumberField({ integer: true }),
      }),
      joust: new SchemaField({
        wins: new NumberField({ integer: true }),
        losses: new NumberField({ integer: true }),
      }),
      passglory: new SchemaField({
        estate: new NumberField({ integer: true }),
        inyear: new NumberField({ integer: true }),
        other: new NumberField({ integer: true }),
      }),
      status: new SchemaField({
        debilitated: new BooleanField(),
        chirurgery: new BooleanField(),
        unconscious: new BooleanField(),
        nearDeath: new BooleanField(),
        madness: new BooleanField(),
        melancholy: new BooleanField(),
        misery: new BooleanField(),
        winter: new BooleanField(),
        train: new BooleanField(),
        economic: new BooleanField(),
        aging: new BooleanField(),
        squireAge: new BooleanField(),
        horseSurv: new BooleanField(),
        familyRoll: new BooleanField(),
        xp: new BooleanField(),
        barren: new BooleanField(),
      }),
      create: new SchemaField({
        stats: new BooleanField({ initial: true }),
        traits: new BooleanField({ initial: true }),
        random: new BooleanField(),
        step: new NumberField({ integer: true, initial: 1 }),
        charSet: new BooleanField(),
        complete: new BooleanField(),
        toggle: new BooleanField({ initial: true }),
        knighted: new BooleanField(),
        parents: new BooleanField(),
        train: new BooleanField(),
        heirStat: new BooleanField(),
      }),
    };
  }
}
