const {
  HTMLField,
  SchemaField,
  NumberField,
  StringField,
  FilePathField,
  ArrayField,
  BooleanField,
} = foundry.data.fields;

export class FollowerData extends foundry.abstract.TypeDataModel {
  static defineSchema() {
    return {
      hp: new SchemaField({
        value: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 10,
        }),
        min: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 0,
        }),
        max: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 10,
        }),
        adj: new NumberField({
          required: false,
          integer: true,
          min: 0,
          initial: 0,
        }),
      }),
      stats: new SchemaField({
        siz: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          formula: new StringField({ required: false }),
        }),
        dex: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        str: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        con: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        app: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
      }),
      subtype: new StringField({ initial: "squire" }),
      notes: new HTMLField(),
      sol: new StringField({ initial: "ordinary" }),
      woundTotal: new NumberField({ integer: true }),
      manMove: new NumberField({ integer: true }),
      manArm: new NumberField({ integer: true }),
      manShd: new NumberField({ integer: true }),
      manMaxHP: new NumberField({ integer: true }),
      manKnockdown: new NumberField({ integer: true }),
      manMjrWnd: new NumberField({ integer: true }),
      manDmg: new NumberField({ integer: true }),
      manHealRate: new NumberField({ integer: true }),
      manUnconscious: new NumberField({ integer: true }),
      squire: new NumberField({ integer: true }),
      born: new NumberField({
        required: true,
        integer: true,
        min: 0,
        initial: 487,
      }),
      culture: new StringField(),
      religion: new StringField(),
      homeland: new StringField(),
      family: new StringField(),
      features: new StringField(),
      heir: new BooleanField(),
      lock: new BooleanField(),
      barren: new BooleanField(),
      view: new BooleanField(),
    };
  }
}
