const {
  HTMLField,
  SchemaField,
  NumberField,
  StringField,
  FilePathField,
  ArrayField,
  BooleanField,
} = foundry.data.fields;

export class FollowerData extends foundry.abstract.TypeDataModel {
  static defineSchema() {
    return {
      hp: new SchemaField({
        value: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 10,
        }),
        min: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 0,
        }),
        max: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 10,
        }),
        adj: new NumberField({
          required: false,
          integer: true,
          min: 0,
          initial: 0,
        }),
      }),
      stats: new SchemaField({
        siz: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          formula: new StringField({ required: false }),
        }),
        dex: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        str: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        con: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        app: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
      }),
      subtype: "squire",
      woundTotal: 0,
      lock: false,
      barren: false,
      heir: false,
      view: false,
      sol: "ordinary",
      squire: 0,
      notes: "",
      born: 487,
      culture: "",
      religion: "",
      homeland: "",
      family: "",
      features: "",
      manArm: 0,
      manShd: 0,
      manMaxHP: 0,
      manKnockdown: 0,
      manMjrWnd: 0,
      manDmg: 0,
      manHealRate: 0,
      manUnconscious: 0,
      manMove: 0,
    };
  }
}
