const {
  HTMLField,
  SchemaField,
  NumberField,
  StringField,
  FilePathField,
  ArrayField,
  BooleanField,
  ObjectField,
} = foundry.data.fields;

export class NpcData extends foundry.abstract.TypeDataModel {
  static defineSchema() {
    return {
      hp: new SchemaField({
        value: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 10,
        }),
        min: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 0,
        }),
        max: new NumberField({
          required: true,
          integer: true,
          min: 0,
          initial: 10,
        }),
        adj: new NumberField({
          required: false,
          integer: true,
          min: 0,
          initial: 0,
        }),
      }),
      stats: new SchemaField({
        siz: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          formula: new StringField({ required: false }),
        }),
        dex: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        str: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        con: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
        app: new SchemaField({
          value: new NumberField({
            required: true,
            integer: true,
            min: 0,
            initial: 10,
          }),
          culture: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          create: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          poison: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          disease: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          sol: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          age: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          major: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          winter: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
          growth: new NumberField({
            required: false,
            integer: true,
            min: 0,
            initial: 0,
          }),
        }),
      }),
      coatOfArms: new FilePathField({
        required: true,
        categories: ["IMAGE"],
        initial: "systems/Pendragon/assets/Icons/checked-shield.svg",
      }),
      gloryAward: new NumberField({ integer: true }),
      gloryTotal: new NumberField({ integer: true }),
      woundTotal: new NumberField({ integer: true }),
      altMove: new NumberField({ integer: true }),
      manMove: new NumberField({ integer: true }),
      valMod: new NumberField({ integer: true }),
      manArm: new NumberField({ integer: true }),
      manShd: new NumberField({ integer: true }),
      manMaxHP: new NumberField({ integer: true }),
      manKnockdown: new NumberField({ integer: true }),
      manMjrWnd: new NumberField({ integer: true }),
      manDmg: new NumberField({ integer: true }),
      manHealRate: new NumberField({ integer: true }),
      manUnconscious: new NumberField({ integer: true }),
      lock: new BooleanField({ initial: false }),
      weaponExp: new BooleanField({ initial: true }),
      armorExp: new BooleanField({ initial: true }),
      skillExp: new BooleanField({ initial: true }),
      traitExp: new BooleanField({ initial: true }),
      passionExp: new BooleanField({ initial: true }),
      horseExp: new BooleanField({ initial: true }),
      talentExp: new BooleanField({ initial: true }),
      noteView: new BooleanField({ initial: false }),
      baseStats: new BooleanField({ initial: false }),
      notes: new HTMLField(),
      altMoveTitle: new StringField({ initial: "Alt Move" }),
      ransom: new StringField(),
      kv: new StringField(),
      random: new ArrayField(new ObjectField()),
    };
  }
}
